### ISSUE TITLE
autojump deletes history

### ISSUE THREAD

**Issue by MosNicholas** [wting/autojump#208]
I've been using autojump on my Mac OSX Lion for the past month or so, and have had to cp the autojump.txt.bac to the autojump.txt file a number of times because the autojump.txt deletes is purged every so often.

**Comment by sxe** [comment]
Same happens to me on archlinux version autojump v22.2.2 with bash.

**Comment by nengxu** [comment]
Copied my comment from #355:

I'm using Arch Linux. Since autojump v22.2.2, like @sxe and @fernandogrd mentioned, the content of ~/.local/share/autojump/autojump.txt is randomly purged. So the history was totally lost. V22.2.4 still has the same problem.

This bug practically makes autojump useless. This is very frustrating to us, long time users of autojump.

@joelthelion @wting Please look into this issue at your earliest convenience. Thanks.

**Comment by nengxu** [comment]
I'm using chruby which may also hook up $PROMPT_COMMAND. 
https://github.com/postmodern/chruby

May this be the cause of this issue?

[neng@dolphin:~]$ echo $PROMPT_COMMAND
printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}" ; autojump_add_to_database

**Comment by wting** [comment]
I have a pretty good idea of the root cause, let's consolidate conversation to #391.
