### ISSUE TITLE
deleted folders never expire

### ISSUE THREAD

**Issue by acornejo** [wting/autojump#390]
autojump does not remove deleted folders from its jump list.

autojump should provide a facility to cleanup unexistent entries, perhaos "autodelete --prune" or something similar.

I've been doing this through the following hack (but a proper solution inside autojump would be much appreciated):

```bash
AUTOJUMP_LOCATION=$(autojump --stat | awk '/data:/ {print $2}')
AUTOJUMP_TEMP=$(mktemp ${TMPDIR:-/tmp}/autojump.XXXXXXX)
while read line; do
    [ -d "$(echo $line | awk '{print $2}')" ] && echo "$line"
done < $AUTOJUMP_LOCATION > $AUTOJUMP_TEMP
mv $AUTOJUMP_TEMP $AUTOJUMP_LOCATION
```

**Comment by acornejo** [comment]
I should add, I am happy to implement this pruning feature in python and submit a pull-request, just don't want to waste work if there is no chance of this getting merged.

**Comment by wting** [comment]
Hey, thanks for opening this issue.

You can remove non-existent paths via `j --purge` (more info: `j --help` or `autojump --help`). The reason this isn't default behavior is because people use network or thumb drives that are mounted / unmounted often.

If this doesn't answer your question, please reopen this issue.
