### ISSUE TITLE
Not jumping to the correct directory sometimes.

### ISSUE THREAD

**Issue by weiHelloWorld** [wting/autojump#411]
I found that sometimes autojump would not jump to the correct directory.

Here is a screenshot: when I tried to switch to "MD_simulation_research" from home directory, autojump led me to "MD_simulation_on_alanine_dipeptide", which is a subdirectory under "MD_simulation_research".  I am wondering if anyone has a similar issue?

Thanks!

<img width="579" alt="capture" src="https://cloud.githubusercontent.com/assets/6883429/14966113/68e24628-1076-11e6-8668-02afc58cf7fc.PNG">

**Comment by jared-hess** [comment]
FYI, this is caused by an indeterminacy introduced in later versions of python with sorting. Basically if it is only sorted by weight, which multiple entries have a tied weight the results returned will be randomized which causes you to cd to the wrong entry. The dev can fix this by adding a secondary sorting attribute that is guaranteed to be unique.

https://github.com/jared-hess/autojump/commit/1fa31610a5c871fb57c4270ef744c6a1e1c0b03b

**Comment by wting** [comment]
@jared-hess: Never knew that about that change in later versions of Python. I guess it's a good way to make sure people don't depend on implicit sorting.

Do you mind submitting a PR for that commit? Or I can go ahead and just make that change directly?

**Comment by jared-hess** [comment]
Submitted. Feel free to look through my dev branch, I've made a number of improvements/fixes for my own use that I haven't bothered to submit PRs for.

**Comment by jared-hess** [comment]
https://github.com/jared-hess/autojump/commits/dev

**Comment by jared-hess** [comment]
By the way, if you want to know when this changed or why this indeterminacy exists take a look at the documentation for PYTHONHASHSEED.
