### ISSUE TITLE
What is the difference between jc and j

### ISSUE THREAD

**Issue by soerenwolfers** [wting/autojump#544]
I really have no idea what 

> Jump To A Child Directory:
> 
> Sometimes it's convenient to jump to a child directory (sub-directory of current directory) rather than typing out the full name.
> 
>                 jc bar

means. I was able to use both `j` and `jc` to jump to both subdirectories and to non-subdirectories. So far, I couldn't find an example where the two behave differently.

Maybe this could be explained more precisely.

**Comment by soerenwolfers** [comment]
After some more testing, it doesn't seem too complicated: `jc bar` will jump to a sub-directory that matches `bar`, if one exists, else it will jump to any directory matching `bar`. The second part was what confused me, I'm not sure if that's intended behavior.

Nonetheless, I'd say the current phrasing does not make sense.

**Comment by wting** [comment]
Open to PRs that clarify docs, but not going to keep this open.

**Comment by himat** [comment]
I have the same question, and I still don't see the difference in the two commands. In order to use `jc`, I still need to have visited the directory right? And isn't every directory just a sub-directory of `/`? So using `j` and `jc` give me the same results. 

An explanation of when to use `jc` would be great.

**Comment by francescoboc** [comment]
> I have the same question, and I still don't see the difference in the two commands. In order to use `jc`, I still need to have visited the directory right? And isn't every directory just a sub-directory of `/`? So using `j` and `jc` give me the same results.
> 
> An explanation of when to use `jc` would be great.

I have exactly the same question. I was thinking that `jc` could be used without having previously visited the directory, but that does not seem to be the case. The current explanation in the manual is very confusing for a new user.

**Comment by wting** [comment]
> After some more testing, it doesn't seem too complicated: `jc bar` will jump to a sub-directory that matches `bar`, if one exists, else it will jump to any directory matching `bar`. The second part was what confused me, I'm not sure if that's intended behavior.
> 
> Nonetheless, I'd say the current phrasing does not make sense.

This is the correct behavior.

`jc` is artificially prioritizing subdirectories (or children in a tree sense) in the case there's multiple matches. This is common in projects where you might have the same folder names (e.g. `src`, `doc`) in each one.

Ideally `j` and `jc` have the same behavior, but gives the user an override when needed.

**Comment by KyrietS** [comment]
I don't understand how it prioritizes children. Consider the following structure
```
~
├── dir_1/
│   └── project_1/
│       └── build
└── dir_2/
    └── project_2/
        └── build
```

And I have `autojump -s`
```
10.0:     /home/user/dir_1/project_1/build
20.0:     /home/user/dir_2/project_2/build
```

When I do `jc` inside `/home/user/`:
```
~ $ jc build
```
It jumps to: `/home/user/dir_2/project_2/build` because it has higher weight. Makes sense.

But when I do `jc` inside `/home/user/dir_1/`:
```
~/dir_1 $ jc build
```
It still jumps to: `/home/user/dir_2/project_2/build`. Why?

If it prioritizes "children" why doesn't it choose `project_1/build`. 

I have to be literally inside `~/dir_1/project_1` for `jc` to jump into `build` that is right there. If it only takes "direct children" into consideration then for me this `jc` option is of very little use. It's almost the same as "cd" but worse because you have to visit the `build` directory at least once before you can use `jc`.

I think `jc` should either:
- jump into "any child" directory, not "direct child" as it is doing now, or
- jump into "direct child" but without this limitation that you have to visit this direct child at least once. This is what @soerenwolfers was thinking the `jc` should do.

In my opinion, the usefulness of `jc` in its current state is questionable.
