### ISSUE TITLE
Prevent Recording Directories in a Subshell

### ISSUE THREAD

**Issue by bigH** [wting/autojump#553]
It'd be really nice to prevent autojump from remembering a directory in a particular subshell. Sometimes shell utilities or scripts that CD in their implementation gunk up my autojump index.

**Comment by bigH** [comment]
Propose `unset_auto_jump; command; set_auto_jump`

**Comment by quchen** [comment]
I had a similar problem, and implemented it as a ZSH alias:

```bash
alias jno='{ chpwd_functions=(${chpwd_functions[@]/autojump_chpwd}) }'
```

This command removes the Autojump hook for the current shell, so that I can now write

```bash
for i in $(find -type d); do (jno; cd $i); done
```

without polluting my Autojump DB.

---

The good thing about this approach is that it’s outside of modifying Autojump itself and it works alright. The bad part is that it’s a bit hacky, and I think the better solution would be for Autojump to check whether a certain environment variable is set in the hook, so that we can write

```bash
for i in $(find -type d); do (AUTOJUMP_DISABLE=; cd $i); done
```

and then writing an Alias for that would be much more user-friendly.
