### ISSUE TITLE
How did you create executable that is readable in Python?

### ISSUE THREAD

**Issue by chimd715** [wting/autojump#668]
`/bin/autojump` file is executable, but also readable file. It's in Python. I've used `pyinstaller` and the executable file is not readable. 
I am wondering how did you create executable that is readable in Python. 
I would really appreciate your answer. Thanks.

**Comment by ThePython10110** [comment]
You can run `python <filename>`, even if `<filename>` doesn't end in `.py`. In other words, the `.py` extension isn't necessary for it to be runnable, it just tells the computer that it's a Python file.

And in UNIX, any file can be marked as executable.

This was probably done so that when trying to run the `autojump` command, it will run `autojump.bat` or `autojump.sh` or whatever instead of the `autojump` file.
