### ISSUE TITLE
zsh: command not found J - Mint Cinnamon

### ISSUE THREAD

**Issue by lonestrangerr** [wting/autojump#678]
Hi, I installed autojump following command
`git clone https://github.com/wting/autojump`

I am in home directory, running following command
`j Downloads`

error returns
`zsh: command not found: j`

**Comment by spydon** [comment]
It's not enough to just clone it, you have to run the installation script too, follow the second paragraph of instructions here: https://github.com/wting/autojump#manual

You don't have to do the manual installation in Linux Mint though, since it is already included in their repositories:
https://community.linuxmint.com/software/view/autojump

**Comment by mk980** [comment]
Thank you, It worked
